Removes proposal on tip disconnection
aguycalled/navcoin-core pull request #10
Opened 2018-08-23 04:18 UTC by red010b37

Should fix this:

https://github.com/NAVCoin/navcoin-core/issues/280

2018-08-23 06:33 UTC, aguycalled commented
could you elaborate what the changes do and why should they fix the issue?

2018-08-23 23:19 UTC, red010b37 commented
In the listproposals RPC command, it loops through and retrieves the proposals with
```
if(pblocktree->GetProposalIndex(vec))
    {
        BOOST_FOREACH(const CFund::CProposal& proposal, vec) {
```

When we invalidate the blocks the tips and payment requests were correctly disconnected but the proposals were never removed and when requested would still return "a list of proposals" that were no longer valid.

This code removes the proposal if the block or blocks before it are invalidated. 

Also, the exploded "if statement" is to help me try and track down the seg fault

2018-08-24 02:57 UTC, aguycalled commented
has this patch been tested?

2018-08-24 03:10 UTC, aguycalled requested changes

2018-08-24 03:10 UTC, aguycalled commented on src/main.cpp
> +    CFund::CProposal propsal;
the variable name looks to have a typo

2018-08-24 03:10 UTC, aguycalled commented on src/main.cpp
> +             if(propsal.blockhash == pindexDelete->GetBlockHash()) {
blockhash points to the block where the proposal was accepted, so this condition is only triggered if the proposal was accepted on the block to disconnect

2018-08-24 03:10 UTC, aguycalled commented on src/main.cpp
> +                 vPropsalsToUpdate.push_back(make_pair(propsal.hash, propsal));
this line does not make any change to the proposal db, as the same object without modification is inserted with the proposal hash as a key

2018-08-24 03:10 UTC, aguycalled commented on src/main.cpp
> +        if (!fHavePruned) {
is this line duplicated?

2018-08-24 03:12 UTC, aguycalled commented
@red010b37 proposals and payment requests are removed on DisconnectBlock() under     // undo transactions in reverse order

2018-08-24 04:53 UTC, red010b37 commented on src/main.cpp
> +    CFund::CProposal propsal;
Fixed

2018-08-24 04:53 UTC, red010b37 commented on src/main.cpp
> +        if (!fHavePruned) {
yea oops

2018-08-26 07:57 UTC, closed without merging